version: '3'

services:
  frontend:
    build:
      context: ./login-demo  # Path to the frontend Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../NODE-REACT-APP  # Path to the backend Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
